_target_: lerobot.common.datasets.data_config.MixtureDataConfigFactory
name: fractal
repo_id: null

data_configs:
  -  ${_load_config:lerobot/conf/robotics_dataset/individual/fractal.yaml}

weights:
  - 1.0