
_target_: lerobot.common.datasets.data_config.LeRobotDroidDataConfigOld

# Dataset identification
name: droid
asset_id: droid
repo_id: droid
root_dir: <path_to_droid_dataset>
episodes_list_file: ${.root_dir}/filter/v1/filtered_episodes.json
validation_episodes: ${.root_dir}/meta/validation_episodes.json

# Action configuration
action_sequence_keys: [action]
action_horizon: 10
action_offset: 1
action_sample_step: 1
state_dim: 7
control_mode: cartesian
map_to_unified_space: false
# Base configuration
base_config:
  _target_: lerobot.common.datasets.data_config.DataConfig  
  local_files_only: true
  prompt_from_task: true 