_target_: lerobot.common.datasets.data_config.LeRobotGalaxeaR1LiteDataConfig

# Dataset identification
name: galaxeaworld
asset_id: galaxeaworld
repo_id: galaxeaworld
root_dir: <path_to_galaxeaworld_dataset>
episodes_list_file: ${.root_dir}/filter/v2/filtered_episodes.json
validation_episodes: ${.root_dir}/meta/validation_episodes.json

# Action configuration
action_sequence_keys: [action]
action_horizon: 10
action_offset: 0
action_sample_step: 2
state_dim: 20
control_mode: joint
map_to_unified_space: false

# Base configuration
base_config:
  _target_: lerobot.common.datasets.data_config.DataConfig
  local_files_only: true
  prompt_from_task: true 