
_target_: lerobot.common.datasets.data_config.LeRobotRDTDataConfig

# Dataset identification
name: rdt
asset_id: rdt
repo_id: rdt
root_dir: <path_to_rdt_dataset>
episodes_list_file: ${.root_dir}/filter/v1/filtered_episodes.json
validation_episodes: ${.root_dir}/meta/validation_episodes.json

# Action configuration
action_sequence_keys: [action]
action_horizon: 10
action_offset: 0
action_sample_step: 1.8
state_dim: 14
control_mode: joint
map_to_unified_space: false
# Base configuration
base_config:
  _target_: lerobot.common.datasets.data_config.DataConfig
  local_files_only: true
  prompt_from_task: true 